apiVersion : apps/v1
kind : Deployment
metadata :
    name : sonarqube-deployment
    namespace : openapi-developer-portal-app-namespace
spec :
    selector :
        matchLabels :
            app : sonarqube
    template :
        metadata :
            labels :
                app : sonarqube
        spec :
            containers :
                -   name : sonarqube
                    image : sonarqube
                    ports :
                        -   containerPort : 9000
                    env :
                        -   name : SONARQUBE_JDBC_URL
                            value : jdbc:postgresql://db:5432/sonar
                        -   name : SONARQUBE_JDBC_USERNAME
                            value : sonar
                        -   name : SONARQUBE_JDBC_PASSWORD
                            value : sonar
                    volumeMounts :
                        -   name : sonarqube-conf
                            mountPath : /opt/sonarqube/conf
                        -   name : sonarqube-data
                            mountPath : /opt/sonarqube/data
                        -   name : sonarqube-extensions
                            mountPath : /opt/sonarqube/extensions
                        -   name : sonarqube-bundled-plugins
                            mountPath : /opt/sonarqube/lib/bundled-plugins
            volumes :
                -   name : sonarqube-conf
                    emptyDir : { }
                -   name : sonarqube-data
                    emptyDir : { }
                -   name : sonarqube-extensions
                    emptyDir : { }
                -   name : sonarqube-bundled-plugins
                    emptyDir : { }

---

apiVersion : v1
kind : Service
metadata :
    name : sonarqube-service
    namespace : openapi-developer-portal-app-namespace
spec :
    selector :
        app : sonarqube
    ports :
        -   protocol : TCP
            port : 9000
            targetPort : 9000

---

apiVersion : networking.k8s.io/v1
kind : NetworkPolicy
metadata :
    name : sonarqube-network-policy
    namespace : openapi-developer-portal-app-namespace
spec :
    podSelector :
        matchLabels :
            app : sonarqube
    ingress :
        -   from :
                -   podSelector :
                        matchLabels :
                            app : mongo
